/* ---------- HighLevel tab ---------- */
function pgHL(){const H=UI.hl;if(!H){if(!UI.hlLoading){UI.hlLoading=true;api('GET',L('/hl/status')).then(r=>{UI.hl=r;UI.hlLoading=false;if(R==='hl')render()}).catch(e=>{UI.hl={error:e.message,configured:false,sync:{},summary:S.hl,log:[]};UI.hlLoading=false;if(R==='hl')render()})}
  return '<div class="phead"><div><h1>HighLevel</h1><p>Checking the connection…</p></div></div>'}
 const ok=H.configured&&H.location&&!H.error;const linked=H.app_location_id===S.id;const O=UI.hlOpts;const sm=H.summary||{};const Vf=UI.hlVerify;
 if(ok&&!O&&!UI.hlOptsLoading){UI.hlOptsLoading=true;api('GET',L('/hl/options')).then(r=>{UI.hlOpts=r;UI.hlOptsLoading=false;if(R==='hl')render()}).catch(()=>{UI.hlOpts={workflows:[],pipelines:[],forms:[],surveys:[],objects:[],products:[],users:[]};UI.hlOptsLoading=false;if(R==='hl')render()})}
 const sw=k=>'<button class="sw '+(H.sync[k]?'on':'')+'" data-a="hlsync" data-k="'+k+'" role="switch" aria-checked="'+(H.sync[k]?'true':'false')+'" aria-label="'+k+'"></button>';
 const sel=(name,val,opts,placeholder,ch)=>'<select class="input" data-ch="'+ch+'" data-k="'+name+'" '+(ok?'':'disabled')+' style="max-width:320px"><option value="">'+placeholder+'</option>'+opts.map(o=>'<option value="'+esc(o.id)+'" '+(o.id===val?'selected':'')+'>'+esc(o.name)+(o.status&&o.status!=='published'?' · '+esc(o.status):'')+'</option>').join('')+'</select>';
 const dis=ok?'':'disabled';const vres=k=>{if(!Vf||!Vf[k])return '<span class="faint">—</span>';const v=Vf[k];if(!v.linked)return '<span class="faint">nothing to check</span>';return v.missing.length?'<span style="color:var(--red)">'+v.ok+'/'+v.checked+' found · missing '+esc(v.missing.slice(0,2).join(', '))+(v.missing.length>2?' +'+(v.missing.length-2):'')+'</span>':'<span style="color:var(--green)">'+v.ok+'/'+v.checked+' found</span>'};
 // 1 · connection
 const conn='<div class="card"><div class="row between wrap"><div><b>Connection</b> <span class="tag '+(ok?'green':H.configured?'red':'amber')+'" style="margin-left:6px">'+(ok?'Connected':H.configured?'Error':'Needs sub-account id')+'</span><div class="small muted">'+(ok?esc(H.location.name)+' · '+esc(H.location.timezone||'')+' · <span class="n">'+esc(H.location.id)+'</span> · '+(linked?'linked to '+esc(V().biz):H.app_location_id?'linked to another business':'not linked to a business yet'):'Token '+(H.token?esc(H.token):'not set')+'. '+esc(H.error||''))+'</div></div><div class="row wrap">'+(ok?(linked?'<button class="btn sm" data-a="hllink" data-k="0">Unlink</button>':'<button class="btn sm p" data-a="hllink" data-k="1">Link '+esc(V().biz)+'</button>'):'')+'<button class="btn sm" data-a="hltest">Test</button><button class="btn sm" data-a="hlrefresh">Refresh</button></div></div>'
  +'<details style="margin-top:8px"><summary class="small muted" style="cursor:pointer">Change sub-account id</summary><form data-form="hlloc" class="row wrap" style="gap:6px;margin-top:8px"><input class="input" name="location_id" placeholder="Sub-account (location) id" value="'+esc(H.location_id||'')+'" style="flex:1;min-width:240px;max-width:420px" id="hl-loc"><button class="btn sm" type="submit">Save</button></form><div class="xs faint" style="margin-top:6px">From the HighLevel URL: app.gohighlevel.com/v2/location/<b>&lt;id&gt;</b>/…</div></details></div>';
 // 2 · sync status table
 const rowsDef=[
  ['contacts','Contacts',sm.contacts+' of '+S.clients.length+' clients','contacts'],
  ['appointments','Calendars',sm.appts+' appointments · '+(sm.services||0)+' of '+S.services.length+' services have a calendar','appointments'],
  ['opportunities','Opportunities',(sm.opportunities||0)+' clients have one'+(H.pipeline&&H.pipeline.id?'':' · no pipeline mapped'),'opportunities'],
  ['workflows','Workflows',Object.values(H.workflows||{}).filter(Boolean).length+' of 5 events mapped',null],
  ['invoices','Payments & invoices',(Vf&&Vf.invoices?Vf.invoices.linked:'—')+' invoices from the desk',null],
  ['email','Email',S.clients.filter(c=>c.email&&c.email.includes('@')).length+' clients have an email',null],
  ['sms','SMS','booking confirmations',null],
  ['objects','Custom objects',(sm.records||0)+' records'+(H.objects&&Object.keys(H.objects).length?'':' · not set up'),'records']];
 const status='<div class="card"><div class="row between wrap"><div><b>Sync status</b><div class="small muted">Switch each domain on or off. Verify reads the newest linked items back from HighLevel.</div></div><div class="row wrap"><button class="btn sm" data-a="hlverify" '+dis+'>'+(UI.hlVerifying?'Verifying…':'Verify')+'</button><button class="btn sm p" data-a="hlseed" '+(ok&&linked?'':'disabled')+'>Seed HighLevel</button></div></div>'
  +'<div class="scrollx"><table style="margin-top:10px"><thead><tr><th style="width:60px">On</th><th>Domain</th><th>Synced</th><th>Verified</th></tr></thead><tbody>'+rowsDef.map(([k,l,c,vk])=>'<tr><td>'+sw(k)+'</td><td><b>'+l+'</b></td><td class="muted">'+c+'</td><td>'+(vk?vres(vk):(k==='invoices'?vres('invoices'):'<span class="faint">—</span>'))+'</td></tr>').join('')+'</tbody></table></div>'
  +(Vf?'<div class="xs '+(Vf.ok?'faint':'')+'" style="margin-top:8px;color:'+(Vf.ok?'var(--green)':'var(--red)')+'">'+(Vf.ok?'Everything linked was found in HighLevel.':'Some linked items were not found; see the rows above.')+'</div>':'')
  +(UI.hlSeed?'<div class="xs faint" style="margin-top:6px">Last seed: '+Object.entries(UI.hlSeed).map(([k,v])=>v+' '+k).join(' · ')+'</div>':'')+'</div>';
 // 3 · set-up (collapsed)
 const wf=H.workflows||{};const wfs=(O&&O.workflows)||[];const pl=H.pipeline||{};const pls=(O&&O.pipelines)||[];const cur=pls.find(p=>p.id===pl.id);const stages=cur?cur.stages:[];const forms=(O&&O.forms)||[];const objs=H.objects||{};
 const det=(title,sub,body,open)=>'<details '+(open?'open':'')+' class="setup"><summary><b>'+title+'</b><span class="muted small"> · '+sub+'</span></summary><div style="padding:10px 0 4px">'+body+'</div></details>';
 const teamBody=S.staff.map(s=>{const u=((O&&O.users)||[]).find(u=>u.id===s.hlUserId);return '<div class="row small" style="padding:5px 0"><b style="width:140px">'+esc(s.name)+'</b><span class="muted grow">'+esc(s.role)+'</span>'+(s.hlUserId?'<span class="tag green">→ '+esc(u?u.name:'HighLevel user')+'</span>':'<span class="tag">not matched</span>')+'</div>'}).join('')+'<button class="btn sm" data-a="hlteam" '+dis+' style="margin-top:6px">Sync team</button>';
 const wfBody='<div class="grid2">'+[['booked','After a booking'],['noshow','After a no-show'],['showed','After a paid visit'],['pass_sold','After a pass is sold'],['pass_expiring','7 days before a pass ends']].map(([k,l])=>'<label class="f">'+l+sel(k,wf[k]||'',wfs,'— not mapped —','hlwf')+'</label>').join('')+'</div><div class="xs faint" style="margin-top:6px">Only published workflows run; drafts are listed for mapping.</div>';
 const plBody='<div class="grid2"><label class="f">Pipeline'+sel('id',pl.id||'',pls,'— choose —','hlpl')+'</label><label class="f">Stage at first booking'+sel('booked',pl.booked||'',stages,'—','hlpl')+'</label><label class="f">Stage after a no-show'+sel('noshow',pl.noshow||'',stages,'—','hlpl')+'</label><label class="f">Stage at first payment (won)'+sel('paid',pl.paid||'',stages,'—','hlpl')+'</label></div>';
 const formBody='<label class="f">Intake form for new clients'+sel('intake',H.intake_form_id||'',forms,'— none —','hlintake')+'</label>'+(forms.length?'<div class="row wrap" style="gap:6px;margin-top:8px">'+forms.map(f=>'<button class="tag" style="border:0;cursor:pointer" data-a="openurl" data-url="'+esc(f.url)+'">'+esc(f.name)+' ↗</button>').join('')+'</div>':'');
 const objBody='<div class="small muted">Pass, Class visit and Shift objects with their fields, linked to the contact.</div><div class="row wrap" style="gap:6px;margin-top:8px">'+Object.entries(objs).map(([k,o])=>'<span class="tag green">'+esc(o.schema)+'</span>').join('')+'</div><div class="row wrap" style="margin-top:8px"><button class="btn sm" data-a="hlobjsetup" '+dis+'>'+(Object.keys(objs).length?'Re-check set-up':'Set up')+'</button><button class="btn sm" data-a="hlobjbackfill" '+(ok&&H.sync.objects?'':'disabled')+'>Backfill records</button></div>';
 const setup='<div class="card"><b>Set-up</b><div class="small muted" style="margin-bottom:4px">Done once per sub-account.</div>'
  +det('Team',(sm.staff||0)+' of '+S.staff.length+' linked to users',teamBody,(sm.staff||0)<S.staff.length)
  +det('Workflows',Object.values(wf).filter(Boolean).length+' of 5 mapped',wfBody,false)
  +det('Pipeline',cur?esc(cur.name):'not mapped',plBody,!cur)
  +det('Forms',H.intake_form_id?'intake form set':'no intake form',formBody,false)
  +det('Custom objects',Object.keys(objs).length?Object.keys(objs).length+' objects':'not set up',objBody,false)+'</div>';
 // 4 · tools
 const tools='<div class="card"><b>Tools</b><div class="row wrap" style="gap:6px;margin-top:8px"><button class="btn sm" data-a="hlimport" '+dis+'>Import contacts</button><button class="btn sm" data-a="hlpush" '+dis+'>Push clients</button><button class="btn sm" data-a="hlsvcpush" '+dis+'>Push services → calendars</button><button class="btn sm" data-a="hlsvcimport" '+dis+'>Import calendars → services</button><button class="btn sm" data-a="hlprod" '+dis+'>Push products</button><button class="btn sm" data-a="hllapsed" '+(ok&&H.sync.email?'':'disabled')+'>Email lapsed clients</button><button class="btn sm" data-a="hltx" '+dis+'>Recent transactions</button></div>'
  +(UI.hltx?(UI.hltx.length?'<div class="scrollx"><table style="margin-top:10px"><thead><tr><th>When</th><th>Contact</th><th>Status</th><th class="r">Amount</th></tr></thead><tbody>'+UI.hltx.map(t=>'<tr><td class="xs">'+esc((t.when||'').slice(0,16).replace('T',' '))+'</td><td>'+esc(t.name||'—')+'</td><td>'+esc(t.status)+'</td><td class="r">'+(t.amount!=null?money(t.amount):'—')+'</td></tr>').join('')+'</tbody></table></div>':'<div class="small faint" style="margin-top:8px">No transactions yet.</div>'):'')+'</div>';
 // 5 · activity
 const logs=(H.log||[]).filter(l=>!UI.hlFailOnly||!l.ok);
 const log='<div class="card"><div class="row between"><b>Activity</b><label class="row xs muted" style="gap:6px;cursor:pointer"><input type="checkbox" data-ch="hlfail" '+(UI.hlFailOnly?'checked':'')+'> failures only</label></div>'+(logs.length?'<div style="margin-top:8px">'+logs.map(l=>'<div class="row small" style="padding:4px 0"><span class="xs faint" style="width:96px;flex:none">'+esc(l.ts.slice(5,16).replace('T',' '))+'</span><span class="xs" style="width:44px;flex:none;color:'+(l.ok?'var(--green)':'var(--red)')+'">'+(l.ok?'ok':'failed')+'</span><span class="grow" style="min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap">'+esc(l.action)+(l.detail?' <span class="muted">· '+esc(l.detail)+'</span>':'')+'</span></div>').join('')+'</div>':'<div class="small faint" style="margin-top:8px">'+(UI.hlFailOnly?'No failures.':'Nothing synced yet.')+'</div>')+'</div>';
 return '<div class="phead"><div><h1>HighLevel</h1><p>Contacts, calendars, opportunities, payments, workflows, forms, email and custom objects, written by the front desk.</p></div></div>'+conn+status+setup+tools+log}
