/* ---------- onboarding ---------- */
function onboarding(){const i=UI.onb;const T=V();const FT=S.features;const slug=S.slug;
 const cats=[...new Set(S.services.map(v=>v.cat))];
 const line='padding:7px 0;border-bottom:1px solid var(--line)';
 const svcRows=S.services.map(v=>'<div class="row between small" style="'+line+'"><span>'+esc(v.em)+' '+esc(v.name)+' <span class="faint">· '+v.dur+' min · '+esc(v.cat)+'</span></span><span class="row" style="gap:8px"><b>'+(v.price?money(v.price):'Free')+'</b><button class="btn xs" data-a="delsvc" data-id="'+v.id+'" title="Remove">✕</button></span></div>').join('');
 const svcForm='<form data-form="onbsvc" class="row wrap" style="gap:6px;margin-top:10px"><input class="input" name="name" placeholder="Add a service" required style="flex:2;min-width:150px" id="onb-svc-name"><input class="input" name="cat" list="onbcats" placeholder="Category" style="flex:1;min-width:110px" id="onb-svc-cat"><datalist id="onbcats">'+cats.map(c=>'<option value="'+esc(c)+'">').join('')+'</datalist><input class="input" name="dur" type="number" value="30" min="5" step="5" style="width:76px" title="Minutes" id="onb-svc-dur"><input class="input" name="price" type="number" value="0" min="0" step="0.5" style="width:86px" title="Price" id="onb-svc-price"><button class="btn p sm" type="submit">Add</button></form><div class="xs faint" style="margin-top:4px">name · category · minutes · price</div>';
 const clsRows=S.classes.map(c=>'<div class="row between small" style="'+line+'"><span>'+esc(c.name)+' <span class="faint">· '+fmtT(c.time)+' · '+c.cap+' seats · '+esc(ST(c.staffId).name.split(' ')[0])+'</span></span><span class="row" style="gap:8px"><b>'+money(c.price)+'</b><button class="btn xs" data-a="delclass" data-id="'+c.id+'" title="Remove">✕</button></span></div>').join('');
 const clsForm=S.staff.length?'<form data-form="onbclass" class="row wrap" style="gap:6px;margin-top:10px"><input class="input" name="name" placeholder="Add a class" required style="flex:2;min-width:150px" id="onb-cls-name"><input class="input" name="time" type="time" value="18:00" style="width:112px" id="onb-cls-time"><input class="input" name="dur" type="number" value="60" min="15" step="5" style="width:76px" title="Minutes" id="onb-cls-dur"><input class="input" name="cap" type="number" value="12" min="1" style="width:72px" title="Seats" id="onb-cls-cap"><input class="input" name="price" type="number" value="20" min="0" style="width:86px" title="Drop-in price" id="onb-cls-price"><select class="input" name="staffId" style="width:auto" id="onb-cls-staff">'+S.staff.map(s=>'<option value="'+s.id+'">'+esc(s.name.split(' ')[0])+'</option>').join('')+'</select><button class="btn p sm" type="submit">Add</button></form><div class="xs faint" style="margin-top:4px">name · start · minutes · seats · drop-in · '+esc(T.staffOne)+' — runs Mon–Sat, edit days later</div>':'';
 const teamRows=S.staff.map(s=>'<div class="row small" style="'+line+'"><span class="av" style="background:'+s.color+'">'+initials(s.name)+'</span><b>'+esc(s.name)+'</b><span class="muted grow">'+esc(s.role)+'</span><span class="faint xs">'+DAYS.filter((d,k)=>s.hours[k]).join(' ')+'</span><button class="btn xs" data-a="delstaff" data-id="'+s.id+'" title="Remove">✕</button></div>').join('');
 const teamForm='<form data-form="onbstaff" class="row wrap" style="gap:6px;margin-top:10px"><input class="input" name="name" placeholder="Add a '+esc(T.staffOne)+'" required style="flex:2;min-width:150px" id="onb-staff-name"><input class="input" name="role" placeholder="Role" style="flex:1;min-width:110px" id="onb-staff-role"><input class="input" name="rate" type="number" value="30" min="0" style="width:86px" title="$ per hour" id="onb-staff-rate"><button class="btn p sm" type="submit">Invite</button></form><div class="xs faint" style="margin-top:4px">Gets a HighLevel login, Mon–Sat hours and every service. Working days are under Team.</div>';
 const tools=[['booking','Online booking page','Guests pick a service, a person and a time at '+slug+'.hl.link/book'],['reminders','Text reminders & receipts','Through HighLevel Conversations; nothing to set up'],['passes',T.passWord,'Sell packs and memberships; redeem at check-in'],['tips','Tips at checkout','15 / 20 / 25% or a typed amount, attributed to the '+T.staffOne]].concat(T.hasClasses?[['classes','Classes with seats','Recurring weekly classes, rosters and drop-in pricing']]:[]).concat([['google','Reserve with Google','Coming soon — bookings straight from your Google profile']]);
 const toolRows=tools.map(([k,l,d])=>'<div class="row" style="padding:9px 0;border-bottom:1px solid var(--line)"><div class="grow"><b class="small">'+esc(l)+'</b><div class="xs muted">'+esc(d)+'</div></div>'+(k==='google'?'<span class="tag">Soon</span>':'<button class="sw '+(FT[k]?'on':'')+'" data-a="feat" data-k="'+k+'" aria-label="'+esc(l)+'" role="switch" aria-checked="'+(FT[k]?'true':'false')+'"></button>')+'</div>').join('');
 const steps=[
  '<h3>What kind of business?</h3><div class="small muted">Sets the words, the starter menu and the sidebar section. Change any of it later.</div><div class="types">'+S.locations.map(l=>'<div class="type '+(S.id===l.id?'on':'')+'" data-a="type" data-k="'+l.id+'" data-stay="1"><span>'+l.emoji+'</span>'+l.label+'</div>').join('')+'</div>',
  '<h3>Your '+T.svc.toLowerCase()+'</h3><div class="small muted">We started you with a typical menu. Remove what you don\'t do and add what you do. The booking page updates the moment you do.</div><div style="max-height:240px;overflow:auto">'+(svcRows||'<div class="faint small">No services yet — add your first one below.</div>')+'</div>'+svcForm+(T.hasClasses?'<h3 style="margin-top:16px">Classes</h3><div style="max-height:160px;overflow:auto">'+(clsRows||'<div class="faint small">No classes yet.</div>')+'</div>'+clsForm:''),
  '<h3>Your team</h3><div class="small muted">Each '+T.staffOne+' gets a HighLevel login and their own lane on the schedule. Hours decide what the booking page offers.</div><div>'+(teamRows||'<div class="faint small">Just you for now? Add yourself.</div>')+'</div>'+teamForm,
  '<h3>Tools</h3><div class="small muted">Switch on what this '+T.label.toLowerCase()+' uses. Anything off is hidden from the front desk and the booking page; switch it back on any time.</div><div>'+toolRows+'</div><div class="card" style="background:var(--card2);margin-top:12px"><b>'+esc(slug)+'.hl.link/book</b><div class="xs muted">'+(FT.booking?'Live now · every booking lands on the front desk':'Booking page is off — turn on "Online booking page" to take bookings online')+'</div></div>'];
 const n=steps.length;const canNext=i!==1||S.services.length>0;
 return '<div class="onb"><div class="in"><div class="brand" style="justify-content:center;color:var(--ink)"><i>HL</i></div><h1 style="font-size:24px">Welcome to your '+T.label.toLowerCase()+', '+esc(T.biz)+'</h1><div class="muted">Four quick steps — about three minutes. Everything can be changed later.</div><div class="dots">'+steps.map((_,k)=>'<i class="'+(k===i?'on':'')+'"></i>').join('')+'</div><div class="box">'+steps[i]+'<div class="row" style="margin-top:8px">'+(i>0?'<button class="btn" data-a="onb" data-k="'+(i-1)+'">Back</button>':'')+'<span class="grow"></span><span class="xs faint">Step '+(i+1)+' of '+n+'</span><button class="btn p" data-a="'+(i<n-1?'onb':'onbdone')+'" data-k="'+(i+1)+'" '+(canNext?'':'disabled title="Add at least one service"')+'>'+(i<n-1?'Next':'Take me to the front desk')+'</button></div></div><button class="btn link" style="margin-top:14px" data-a="onbdone">Skip for now — take me to my '+T.label.toLowerCase()+'</button></div></div>'}
