/* ---------- schedule ---------- */
function pgSched(){const d=UI.sched;const w=dow(parse(d));const isToday=d===TODAY;const hours=S.staff.map(s=>s.hours[w]).filter(Boolean);const classes=(S.features.classes?S.classes:[]).filter(c=>c.days.includes(w));const dayAppts=S.appts.filter(a=>a.date===d&&a.status!=='cancelled');
 let start=hours.length?Math.min(...hours.map(h=>mins(h[0]))):mins(S.rules.open),end=hours.length?Math.max(...hours.map(h=>mins(h[1]))):mins(S.rules.close);
 classes.forEach(c=>{start=Math.min(start,Math.floor(mins(c.time)/30)*30);end=Math.max(end,Math.ceil((mins(c.time)+c.dur)/30)*30)});dayAppts.forEach(a=>{start=Math.min(start,Math.floor(mins(a.time)/30)*30);end=Math.max(end,Math.ceil((mins(a.time)+SV(a.serviceId).dur)/30)*30)});
 const rows=[];for(let m=start;m<end;m+=30)rows.push(m);const H=48;const px=m=>(m-start)/30*H;
 const lane=st=>{const h=st.hours[w];const mine=dayAppts.filter(a=>a.staffId===st.id);
  const off=h?'<div class="offband" style="top:0;height:'+px(mins(h[0]))+'px"></div><div class="offband" style="top:'+px(mins(h[1]))+'px;height:'+Math.max(0,px(end)-px(mins(h[1])))+'px"></div>':'';
  const items=mine.map(a=>{const sv=SV(a.serviceId);const c=C(a.clientId);const late=isToday&&a.status==='booked'&&mins(a.time)<nowMins();const short=sv.dur<=30;
   return '<div class="blk '+a.status+(late?' late':'')+(short?' short':'')+'" style="top:'+(px(mins(a.time))+2)+'px;height:'+(sv.dur/30*H-4)+'px;--c:'+st.color+'" data-a="appt" data-id="'+a.id+'" title="'+esc(c.name)+' · '+esc(sv.name)+' · '+fmtT(a.time)+'–'+fmtT(endOf(a))+'"><div class="row" style="gap:6px;min-width:0"><b class="grow nm">'+esc(c.name)+'</b><span class="st">'+(a.status==='arrived'?'checked in':a.status==='done'?'paid':a.status==='noshow'?'no-show':late?'late':'')+'</span></div>'+(short?'':'<span class="g nm">'+esc(sv.name)+' · '+fmtT(a.time)+'–'+fmtT(endOf(a))+(activePass(c,sv)?' · <span style="color:var(--violet)">pass</span>':'')+'</span>')+'</div>'}).join('')
   +classes.filter(c=>c.staffId===st.id).map(c=>{const n=(S.attend[c.id+'_'+d]||[]).length;return '<div class="blk cls" style="top:'+(px(mins(c.time))+2)+'px;height:'+(c.dur/30*H-4)+'px" data-a="roster" data-id="'+c.id+'" data-date="'+d+'" title="'+esc(c.name)+' · '+n+' of '+c.cap+' seats"><b class="nm">'+esc(c.name)+'</b><span class="g nm">'+fmtT(c.time)+' · '+n+'/'+c.cap+' seats'+(n>=c.cap?' · full':'')+'</span><div class="bar"><i style="width:'+Math.min(100,c.cap?n/c.cap*100:0)+'%"></i></div></div>'}).join('');
  const nowline=isToday&&nowMins()>=start&&nowMins()<=end?'<div class="nowline" style="top:'+px(nowMins())+'px"></div>':'';
  return '<div class="lane '+(h?'':'off')+'" style="height:'+(rows.length*H)+'px" data-a="lane" data-sid="'+st.id+'" data-date="'+d+'" data-start="'+start+'">'+(h?off:'<div class="xs faint" style="padding:8px">Day off</div>')+items+nowline+'</div>'};
 const head=st=>{const h=st.hours[w];const mine=dayAppts.filter(a=>a.staffId===st.id);const booked=sum(mine,a=>SV(a.serviceId).dur);return '<div class="hd"><span class="av" style="background:'+st.color+'">'+initials(st.name)+'</span><div class="grow" style="min-width:0"><b class="nm" style="display:block">'+esc(st.name)+(st.clockIn&&isToday?' <span style="color:var(--green)" title="Clocked in">●</span>':'')+'</b><span class="xs faint">'+(h?fmtT(h[0])+'–'+fmtT(h[1])+' · '+mine.length+' appt'+(mine.length===1?'':'s')+(booked?' · '+(booked/60).toFixed(1)+'h':''):'off today')+'</span></div></div>'};
 const days=Array.from({length:7},(_,i)=>{const x=iso(addD(now(),i));const n=S.appts.filter(a=>a.date===x&&a.status!=='cancelled').length;const dd=parse(x);return '<button class="day '+(x===d?'on':'')+'" data-a="sday" data-d="'+x+'" aria-label="'+DAYS[dow(dd)]+' '+dd.getDate()+', '+n+' appointments"><span class="dn">'+(i===0?'Today':DAYS[dow(dd)]+' '+dd.getDate())+'</span>'+(n?'<span class="dc">'+n+'</span>':'')+'</button>'}).join('');
 const total=dayAppts.length;const live=dayAppts.filter(a=>['booked','arrived'].includes(a.status)).length;
 return '<div class="phead"><div><h1>Schedule</h1><p>'+rel(d)+' · '+total+' appointment'+(total===1?'':'s')+(isToday&&total?' · '+live+' still to come':'')+(classes.length?' · '+classes.length+' class'+(classes.length===1?'':'es'):'')+'. Click an empty slot to book.</p></div><div class="row wrap"><div class="days">'+days+'</div>'+(isToday?'<button class="btn sm" data-a="tonow" title="Scroll to the current time">Now</button>':'')+'<button class="btn sm p" data-a="book">Book</button></div></div>'
 +'<div class="schedwrap" id="schedwrap"><div class="sched" style="--cols:'+S.staff.length+'"><div class="hd tcol"></div>'+S.staff.map(head).join('')+'<div class="tcol">'+rows.map(m=>'<div class="t'+(m%60===0?' hr':'')+'">'+(m%60===0?fmtT(tstr(m)):'')+'</div>').join('')+'</div>'+S.staff.map(lane).join('')+'</div></div>'
 }
